[package]
name = "com_github_kicsyromy_kinesix"
version = "0.1.0"
authors = ["Romeo Calota <kicsyromy@gmail.com>"]
edition = "2018"

[dependencies]
kinesix = { path = "./lib" }

[dependencies.gtk]
version = "0.7.0"
features = ["v3_20"]

[dependencies.gio]
version = "0.7.0"
features = ["v2_44"]

