[package]
name = "Kinesix"
version = "0.1.0"
authors = ["Romeo Calota <kicsyromy@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
input = "0.4.1"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_20"]

[dependencies.gio]
features = ["v2_44"]

